# Generated by Django 3.2.4 on 2021-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruitname', models.CharField(max_length=100, null=True, verbose_name='Fruitname')),
                ('ftype', models.CharField(max_length=100, null=True, verbose_name='Fruit Type')),
            ],
            options={
                'verbose_name': 'Fruit',
                'verbose_name_plural': 'Fruits',
            },
        ),
    ]
